config/routes.rb
Rails.application.routes.draw do
  root to: 'documents#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "status", to: "pages#status", as: :status

  resources :documents, only: [:index, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :documents, only: [ :index ]
      get "documents/*number", to: "documents#show"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  validates :number, presence: { message: "CPF cannot be blank." }
  validates :number, uniqueness: { message: "CPF already blocked" }, on: :create
  validates :number, length: { is: 11, message: "CPF must have 11 digits." }
  validates :number, format: { with: /\A\d{11}\z/, message: "CPF must have only numbers" }
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def not_found(exception)
    render json: { error: exception.message }, status: :not_found
  end
end

app/controllers/api/v1/documents_controller.rb
class Api::V1::DocumentsController < Api::V1::BaseController
  before_action :set_document, only: :show
  def index
    @documents = Document.all
  end

  def show
  end

  private

  def set_document
    @document = Document.find_by(number: params[:number])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def index
    @new_document = Document.new

    @documents = Document.all
    @search = params["search"]
    if @search.present?
      @number = @search["number"].gsub(/[-\.]/, '')
      @document = Document.where(number: @number).last
      if @document.nil?
        return @document_number = @number
      end
      @document_number = @document.number
    end
  end

  def create
    document = Document.new(document_params)
    if document.save
      redirect_to documents_path, notice: 'Document number added successfully.'
    else
      render :index
    end
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    redirect_to documents_path, notice: "Document number excluded successfully"
  end

  private

  def document_params
    params.require(:document).permit(:number)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def status
    @document_count = Document.count
    @uptime = BrazilianCitizenNumberBlacklistChecker::BOOTED_AT
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/citizens_numbers/index.html.erb
<div class="container">
  <%= simple_form_for :search, url: root_path, method: "GET" do |f| %>
    <%= f.input :number, input_html: {value: ""} %>
    <%= f.submit "Search", class: "btn btn-primary" %>
  <% end %>
  <% unless @citizen_number.nil? %>
    <div class="col-xs-12 col-sm-8 offset-sm-2">
      <h1>CPF: <%= @citizen_number.number %></h1>
    </div>
  <% end %>
</div>

app/views/documents/index.html.erb
<div class="document-container">
  <div class="mt-4">
    <h1 class="d-flex justify-content-center border-bottom text-center">"CPF" Blacklist</h1>

    <h3 class="mt-5">This is a database created to blacklist CPF numbers. And what is a CPF?</h3>
    <p class="mt-4 border-bottom">
      "CPF" stands for <em>"Cadastro de Pessoas Físicas"</em> (Natural Persons Register).
      A CPF is an individual taxpayer identification number given to people living in Brazil,
      both native Brazilians and resident aliens, who pay taxes.
    </p>
  </div>
  <div class="mt-4">
    <%= simple_form_for :search, url: root_path, input_html: {id: :form}, method: "GET" do |f| %>
      <%= f.input :number, input_html: {value: "", id: :cpf}, label: "CPF number:", placeholder: "E.g. 000.000.000-00" %>
      <div class="errors">
        <ul class="errors-list">
        </ul>
      </div>
      <%= f.submit "Search on the blacklist", id: "search-button", class: "btn btn-secondary rounded-pill w-100" %>
    <% end %>
  </div>
  <% if @document.present? %>
    <div class="result mt-4">
      <div>
        <div>
          <h5>CPF: <%= @document_number %></h5>
          <h3><strong>BLOCK</strong></h3>
        </div>
        <div>
          <%= link_to "Remove from blacklist", document_path(@document), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: "btn btn-danger rounded-pill w-100" %>
        </div>
      </div>
    </div>
  <% end %>
  <% if @document.nil? && @document_number.present? %>
    <div class="result mt-4">
      <h5>CPF: <%= @document_number %></h5>
      <h3><strong>FREE</strong></h3>
      <%= simple_form_for (@new_document), remote: true do |f| %>
        <%= f.input :number, as: :hidden, input_html: { value: @document_number } %>
        <%= f.submit 'Add to the blacklist', data: { confirm: 'Are you sure?' }, class: 'btn btn-dark rounded-pill w-100' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/documents/show.html.erb
<div class="container">
  <%= simple_form_for :search, url: root_path, method: "GET" do |f| %>
    <%= f.input :number, input_html: {value: ""} %>
    <%= f.submit "Search", class: "btn btn-primary" %>
  <% end %>
  <% unless @document.nil? %>
    <div class="col-xs-12 col-sm-8 offset-sm-2">
      <h1>CPF: <%= @document.number %></h1>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocumentNumberBlacklistChecker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/status.html.erb
<div class="status-container">
  <div>
    <h1 class="mt-3 border-bottom"><strong>STATUS</strong></h1>
  </div>
  <div class="mt-4 border-bottom">
    <h3>Our blacklist contains <strong><%= @document_count %></strong> "CPF" numbers.</h3>
  </div>
  <br>
  <div>
    <h3>The server is up for <strong><%= time_ago_in_words(@uptime) %></strong></h3>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>